#389 - filter logs
wttech/cogboard pull request #422
Opened 2021-11-20 19:20 UTC by clmrv

## Description
Filters logs on front, based on added regular expressions. Filters are saved in browser's local storage.

## Motivation and Context
#386 #389  #390

## Screenshots (if appropriate)
<img width="423" alt="image" src="https://user-images.githubusercontent.com/50049833/142738361-b0d38118-7a29-40db-97ff-e9fc55330a1b.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/50049833/142738396-f6916ad9-5d86-4ce6-8da7-f9b49b753ac3.png">
<img width="504" alt="image" src="https://user-images.githubusercontent.com/50049833/142738385-78adf34b-446f-4faa-82d8-ed58d5d778dd.png">
<img width="423" alt="image" src="https://user-images.githubusercontent.com/50049833/142738375-85830ee5-6292-492f-bfc5-85f4001a1019.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the [code style](https://github.com/wttech/cogboard/blob/master/CONTRIBUTING.md#coding-conventions) of this project.
- [ ] My change requires a change to the documentation.
- [ ] Automated functional tests have been added or modified to cover my changes (if applicable)
- [ ] I have updated the documentation accordingly.

---

I hereby agree to the terms of the Cogboard Contributor License Agreement.

2021-11-21 12:30 UTC, janeksmielowski requested changes

2021-11-21 12:30 UTC, janeksmielowski commented on cogboard-webapp/src/components/SettingsMenu/index.js
> +            deleteAction={id => dispatch(deleteAction(id))}
dlaczego przenieślismy tego dispatcha wyżej?

2021-11-21 12:30 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
> +  const filterByRegExp = (log, filters) => {
Filtrowanie miało się odbywać na backendzie. Filtry trzymamy na froncie (to jest dobrze), ale po zatwierdzeniu filtra musi iść call do backendu, żeby ten od tej pory wysyłał do mnie tylko filtrowane logi (ale składowanie bez zmian - do tego będzie kwarantanna). Dodatkowo martwi mnie nieoptymalność tej funkcji. Jak będziemy to robić na backendzie, to zadbajmy proszę o to, bo tutaj widzę sporo logiki i niepotrzebnych pętli, a funkcja jest aplikowana dla każdego loga (więcej logów = więcej czasu na przetworzenie)

2021-11-21 12:30 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/AdvancedFiltersMenu/FilterForm.js
> +        data-cy="endpoint-form-submit-button"
tutaj rozumiem, że nie ma onClick, bo guzik działa jako submission input tak?

2021-11-21 12:30 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/AdvancedFiltersMenu/index.js
> +    const maxId = filters.reduce((acc, { id }) => (id > acc ? id : acc), 0);
czy nie byłoby lepiej nadawać coś bardziej unikalnego niż liczba porządkowa? na przykład jakiś generowany uuid?

2021-11-21 12:30 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/helpers.js
> +export const setFilters = (
Zmieniłbym nazwę na saveFilters, bo lepiej sugeruje, że zachowujemy coś w storage'u. Set oznacza, że tylko coś ustawiamy. Fajnie ograna ta funkcja btw :)

2021-11-24 16:17 UTC, clmrv commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/helpers.js
> +export const setFilters = (
Zmienione

2021-11-24 16:18 UTC, clmrv commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/AdvancedFiltersMenu/index.js
> +    const maxId = filters.reduce((acc, { id }) => (id > acc ? id : acc), 0);
Faktycznie, cały projekt korzysta z biblioteki generującej uuid. Dodane

2021-11-24 16:18 UTC, clmrv commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/Toolbar/FilterPicker/AdvancedFiltersMenu/FilterForm.js
> +        data-cy="endpoint-form-submit-button"
Tak, wzorowane na istniejących formularzach

2021-11-24 16:22 UTC, clmrv commented on cogboard-webapp/src/components/SettingsMenu/index.js
> +            deleteAction={id => dispatch(deleteAction(id))}
Dzięki temu mogliśmy użyć tego komponentu, w przypadku bez dispatcha

2021-11-25 07:24 UTC, janeksmielowski approved these changes

2021-11-25 07:24 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
> +  const filterByRegExp = (log, filters) => {
UPDATE 25.11: Wszystkie filtrowania robimy NA FRONCIE

2021-11-26 15:35 UTC, merged