#436 | log list wirtualization
wttech/cogboard pull request #446
Opened 2021-12-08 19:33 UTC by clmrv

## Description
Add log list virtualization
Also sets up following logs (to be improved)

## Motivation and Context
#436

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the [code style](https://github.com/wttech/cogboard/blob/master/CONTRIBUTING.md#coding-conventions) of this project.
- [ ] My change requires a change to the documentation.
- [ ] Automated functional tests have been added or modified to cover my changes (if applicable)
- [ ] I have updated the documentation accordingly.

---

I hereby agree to the terms of the Cogboard Contributor License Agreement.

2021-12-10 17:54 UTC, janeksmielowski requested changes

2021-12-10 17:54 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
> +      console.log(scrollerRef.current.scrollTop);
wywalmy console logi

2021-12-10 17:54 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
> +    console.log(scroll);
j/w

2021-12-10 17:54 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/index.js
> +          itemContent={index => {
wynieśmy to całe do funkcji

2021-12-10 17:54 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/styled.js
> +    margin: 0.5em 0 !important;
wolałbym nie zaszywać !importantów w kodzie. Spróbujmy zamiast tego skonstruować silniejszy selektor. Na przykład podwójny ampersand `&&.Mui-expanded`

2021-12-11 15:46 UTC, clmrv commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/styled.js
> +    margin: 0.5em 0 !important;
Fajny trik z tym `&&`

2021-12-12 11:18 UTC, janeksmielowski commented on cogboard-webapp/src/components/widgets/types/LogViewerWidget/LogList/styled.js
> +    margin: 0.5em 0 !important;
😎

2021-12-12 11:18 UTC, janeksmielowski approved these changes

2021-12-12 11:21 UTC, merged